name: talent_list
description: A Flutter project for listing talents.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  bloc_concurrency: ^0.1.0
  remote_talent_api:
    path: packages/remote_talent_api
  talent_repository:
    path: packages/talent_repository
  equatable: ^2.0.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/album_placeholder.jpg
